### ISSUE TITLE
[FR] readline integration

### ISSUE THREAD

**Issue by dcolascione** [astoff/drepl#2]
This library would be killer if it were integrated in readline. At a stroke, we'd have dynamic, robust completion support for bash, GDB, and myriad other programs. I'd been meaning to do something like this myself for years. Maybe we're almost here!

**Comment by astoff** [comment]
I tried some things but don't quite see a good way, for instance, to make a bash dREPL. So I wil close this ticket that has been lingering here for a while, but feel free to start another discussion if you have ideas.

**Comment by dcolascione** [comment]
A bash (or readline more generally) drepl would be exactly like shell-mode, but with Emacs based completion, multi-line editing, and so on. Seems feasible to me. Granted, core readline changes would be needed, but it's possible to make these changes.
