### ISSUE TITLE
can't run drepl-ipython

### ISSUE THREAD

**Issue by pank** [astoff/drepl#4]
Hi,

I have installed v0.3 from ELPA on windows using Anaconda python v3.11 or v3.12.

I wanted to try this project as I miss `comint` when using `emacs-jupyter`.

However, the python process stops before drepl is started:

```
Python 3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.15.0 -- An enhanced Interactive Python. Type '?' for help.

Do you really want to exit ([y]/n)? 

Process dnatplot/*IPython* finished
```

I don't fully understand the initialization process, but it seems `drepl--init` calls `python -c "import sys; exec(''.join(sys.stdin)); Drepl.instance().mainloop()"` via the ipython `drepl--command`. drepl-ipython.py is then sent as stdin (I'm curious why `Drepl.instance().mainloop()` couldn't just be run if `__name__ == '__main__'`?). 

The log isn't very revealing either: 
```
[11:42:21] starting dnatplot/*IPython*
[11:42:23] read {"op": "getoptions"}
[11:42:23] send msg {"id":1,"op":"setoptions","prompts":["In [{}]: ","...: ","\u001B[31mOut[{}]:\u001B[0m ","\n",""]}
[11:42:23] read {"op": "status", "status": "ready"}
[11:42:23] read {"op": "status", "status": "rawio"}
```

It seems that the EOFError exception in the `Drepl.mainloop` method is triggered. when I change the default to 'n' in the exit question, the error get triggered continuously.

I'm not quite sure how to debug this further. Any ideas?

**Comment by astoff** [comment]
Okay, I'm pretty sure this is related to the fact you're using Windows. Certainly it's necessary that the IPython subprocess runs in a PTY as opposed to via pipes. I guess you can check that by running `M-: (process-tty-name (get-buffer-process (current-buffer))) RET` in the dREPL buffer.

You could modify the way initialization works, e.g. by just calling `python path/to/drepl-ipython.py`. The disadvantage (and reason for the more contrived initalization) is that this will not work over Tramp, since drepl-ipython.py is not present in the remote machine.

If we are able to confirm that the contrived initalization cannot work on Windows, then I would add a simpler, Tramp-incompatible workaround for Windons only.

> I'm curious why `Drepl.instance().mainloop()` couldn't just be run if `__name__ == '__main__'`?

I guess you're right ;-).

**Comment by astoff** [comment]
Okay, `python -i` is not the right way to do it. What you would need is:

1. Add the `if __name__ == "__main__"` trick to drepl-ipython.py (which is a change I just pushed to Github)
2. Change the following 2 methods:

```elisp
(cl-defmethod drepl--command ((_ drepl-ipython))
  `(,python-interpreter ,drepl-ipython--start-file))

(cl-defmethod drepl--init ((repl drepl-ipython))
  (cl-call-next-method repl)
  (drepl--adapt-comint-to-mode ".py")
  (push '("5151" . comint-mime-osc-handler) ansi-osc-handlers))
```

Again, this is what one would need to do to run the process over pipes (as opposed to a PTY). But ideally I would like to find out why the PTY solution is not working on Windows.

**Comment by pank** [comment]
I will try this on Monday when I turn on my windows pc again.

10 Aug 2024 09.49.41 Augusto Stoffel ***@***.***>:

**Comment by pank** [comment]
With the new version of `drepl-ipython.{py, el}` and the two changes above I can run `drepl-ipython` and completions and plots work as expected (based on very brief testing).

**Comment by astoff** [comment]
Okay, thanks for bringing to my attention that Windows doesn't have PTYs. I still need to think how to best work around this limitation.

**Comment by astoff** [comment]
@pank If you would like to, feel free to test this branch: https://github.com/astoff/drepl/pull/5
